# 6_dispatch_alert.py
import json
import requests

# Load the latest alert telemetry payload generated by Phase 6
try:
    with open("latest_telemetry_alert.json", "r") as f:
        alert_data = json.load(f)
except FileNotFoundError:
    print("❌ Error: 'latest_telemetry_alert.json' missing. Run 5_auto_evaluator.py first.")
    exit(1)

# Construct a rich message body for Slack / Discord / Teams webhooks
status_emoji = "🚨" if alert_data["status"] == "ALERT" else "✅"
metrics = alert_data["metrics"]

message = {
    "text": f"{status_emoji} *ARGUS MLOps Telemetry Alert*",
    "attachments": [
        {
            "color": "#FF0000" if alert_data["status"] == "ALERT" else "#00FF00",
            "fields": [
                {"title": "Status", "value": alert_data["status"], "short": True},
                {"title": "Action Required", "value": str(alert_data["action_required"]), "short": True},
                {"title": "Anomaly Rate", "value": f"{metrics['anomaly_percentage']:.2f}%", "short": True},
                {"title": "Feature Drift Rate", "value": f"{metrics['drifted_features_percentage']:.2f}% ({metrics['drifted_feature_count']} features)", "short": True}
            ]
        }
    ]
}

# Webhook simulation logic
WEBHOOK_URL = "https://httpbin.org/post"  # Dummy testing endpoint

print("📡 Dispatching telemetry alert payload to incident channel...")
response = requests.post(WEBHOOK_URL, json=message)

if response.status_code == 200:
    print("✅ Alert successfully delivered to incident webhook target.")
    print("Payload summary dispatched:")
    print(json.dumps(message, indent=2))
else:
    print(f"❌ Failed to dispatch webhook. Server returned status: {response.status_code}")